deployment:
  tasks:
    - export NVM_DIR="$HOME/.nvm"
    - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Load nvm
    - nvm use node  # Replace with your required Node.js version
    - export REPOPATH=$HOME/repositories/locaplus
    - export DEPLOYPATH=$HOME/public_html
    - cd $REPOPATH && npm install
    - cd $REPOPATH && npm run build
    - rsync -av --delete $REPOPATH/build/ $DEPLOYPATH/
    - echo "Deployment completed with nvm"
