export const SECTIONS = {
  en: {
    HOME: 'home',
    ABOUT: 'about',
    PRODUCTS: 'products',
    CONTACT: 'contact',
    QUOTE: 'quote',
    CAREERS: 'careers',
    TEMPOS: 'tempos',
    POPULAR_SHELTERS: 'popular-shelters',
    WHY_CHOOSE_US: 'why-choose-us',
    FAQ: 'FAQ',
  },
  fr: {
    HOME: 'accueil',
    ABOUT: 'a propos',
    PRODUCTS: 'produits',
    CONTACT: 'contact',
    QUOTE: 'soumission',
    CAREERS: 'carrieres',
    TEMPOS: 'abris-tempo',
    POPULAR_SHELTERS: 'abris-populaires',
    WHY_CHOOSE_US: 'pourquoi-nous-choisir',
    FAQ: 'FAQ',
  },
} as const;
